### PR TITLE
 allows to build time displayed on the side border

### PR DESCRIPTION
**Pull request by Dekhnar**

### CODE REVIEW

**Comment by Dekhnar** [comment]
Fixed #53  @Skyost

**Comment by Skyost** [comment]
It seems good to me. Maybe just one little detail : could you please rename `SideTimeBuilder` into something like `HoursColumnTimeBuilder` (for better consistency) ?

**Comment by Dekhnar** [comment]
@Skyost I rename the builder 😃 .

**Comment by Skyost** [comment]
Top ! :wink:

**Pull request merged**
